DROP TABLE IF EXISTS G20_Joueur ;
DROP TABLE IF EXISTS G20_Equipe ;

CREATE TABLE G20_Equipe (
    id_equipe SERIAL PRIMARY KEY, 
    nom_equipe VARCHAR(100) NOT NULL,
    ville VARCHAR(100) NOT NULL
);

INSERT INTO G20_Equipe (nom_equipe, ville) VALUES
('Lyon Olympique', 'Lyon'),
('Stade Français Paris Rugby', 'Paris'),
('Stade Toulousain', 'Toulouse'),
('Union Bordeaux-Bègles', 'Bordeaux'),
('Stade Rochelais', 'La Rochelle');

CREATE TABLE G20_Joueur (
    id_joueur SERIAL PRIMARY KEY,  
    nom_joueur VARCHAR(100) NOT NULL,
    jou_nationalite VARCHAR(50) NOT NULL,
    jou_taille INT NOT NULL,
    jou_poids INT NOT NULL,
    jou_poste VARCHAR(100) NOT NULL CHECK (jou_poste IN ('Pilier', 'Talonneur', '2ème ligne', '3ème ligne', 'Mêlée', 'Ouverture', 'Centre', 'Ailier', 'Arrière')),
    id_equipe INT,
    FOREIGN KEY (id_equipe) REFERENCES G20_Equipe(id_equipe)
);

INSERT INTO G20_Joueur (nom_joueur, jou_nationalite, jou_taille, jou_poids, jou_poste, id_equipe) VALUES
('Cedate GOMES SA', 'Portugal', 185, 113, 'Pilier', (select id_equipe from G20_Equipe where ville = 'Lyon')),
('Hamza KAABÈCHE', 'France', 189, 118, 'Pilier',  (select id_equipe from G20_Equipe where ville = 'Lyon')),
('Jermaine AINSLEY', 'Nouvelle-Zélande', 181, 127, 'Pilier',  (select id_equipe from G20_Equipe where ville = 'Lyon')),
('Jérôme REY', 'France', 183, 133, 'Pilier',  (select id_equipe from G20_Equipe where ville = 'Lyon')),
('Sébastien TAOFIFENUA', 'France', 178, 130, 'Pilier',  (select id_equipe from G20_Equipe where ville = 'Lyon')),
('Guillaume MARCHAND', 'France', 183, 102, 'Talonneur',  (select id_equipe from G20_Equipe where ville = 'Lyon')),
('Sam MATAVESI', 'Fidji', 183, 111, 'Talonneur', (select id_equipe from G20_Equipe where ville = 'Lyon')),
('Yanis CHARCOSSET', 'France', 184, 104, 'Talonneur', (select id_equipe from G20_Equipe where ville = 'Lyon')),
('Alban ROUSSEL', 'France', 196, 120, '2ème ligne', (select id_equipe from G20_Equipe where ville = 'Lyon')),
('Félix LAMBEY', 'France', 196, 106, '2ème ligne', (select id_equipe from G20_Equipe where ville = 'Lyon')),
('Killian GÉRACI', 'France', 200, 118, '2ème ligne', (select id_equipe from G20_Equipe where ville = 'Lyon')),
('Mickaël GUILLARD', 'France', 197, 113, '2ème ligne', (select id_equipe from G20_Equipe where ville = 'Lyon')),
('Tomás LAVANINI', 'Argentine', 201, 127, '2ème ligne', (select id_equipe from G20_Equipe where ville = 'Lyon')),
('Arno BOTHA', 'Afrique du sud', 190, 108, '3ème ligne', (select id_equipe from G20_Equipe where ville = 'Lyon')),
('Beka SAGINADZE', 'Géorgie', 192, 110, '3ème ligne', (select id_equipe from G20_Equipe where ville = 'Lyon')),
('Beka SHVANGIRADZE', 'Géorgie', 191, 104, '3ème ligne', (select id_equipe from G20_Equipe where ville = 'Lyon')),
('Dylan CRETIN', 'France', 195, 105, '3ème ligne', (select id_equipe from G20_Equipe where ville = 'Lyon')),
('Liam ALLEN', 'Nouvelle-Zélande', 191, 105, '3ème ligne', (select id_equipe from G20_Equipe where ville = 'Lyon')),
('Maxime GOUZOU', 'France', 189, 106, '3ème ligne', (select id_equipe from G20_Equipe where ville = 'Lyon')),
('Pierre-Samuel PACHECO', 'France', 192, 115, '3ème ligne', (select id_equipe from G20_Equipe where ville = 'Lyon')),
('Steeve BLANC-MAPPAZ', 'France', 190, 103, '3ème ligne', (select id_equipe from G20_Equipe where ville = 'Lyon')),
('Théo WILLIAM', 'France', 194, 109, '3ème ligne', (select id_equipe from G20_Equipe where ville = 'Lyon')),
('Baptiste COUILLOUD', 'France', 176, 83, 'Mêlée', (select id_equipe from G20_Equipe where ville = 'Lyon')),
('Charlie CASSANG', 'France', 173, 92, 'Mêlée', (select id_equipe from G20_Equipe where ville = 'Lyon')),
('Martin PAGE-RELO', 'France', 173, 77, 'Mêlée', (select id_equipe from G20_Equipe where ville = 'Lyon')),
('Fletcher SMITH', 'Nouvelle-Zélande', 180, 88, 'Ouverture', (select id_equipe from G20_Equipe where ville = 'Lyon')),
('Léo BERDEU', 'France', 195, 99, 'Ouverture', (select id_equipe from G20_Equipe where ville = 'Lyon')),
('Paddy JACKSON', 'Irlande', 180, 89, 'Ouverture', (select id_equipe from G20_Equipe where ville = 'Lyon')),
('Alfred PARISIEN', 'France', 182, 93, 'Centre', (select id_equipe from G20_Equipe where ville = 'Lyon')),
('Josiah MARAKU', 'Nouvelle-Zélande', 180, 97, 'Centre', (select id_equipe from G20_Equipe where ville = 'Lyon')),
('Semi RADRADRA', 'Fidji', 188, 105, 'Centre', (select id_equipe from G20_Equipe where ville = 'Lyon')),
('Théo MILLET', 'France', 189, 99, 'Centre', (select id_equipe from G20_Equipe where ville = 'Lyon')),
('Thibaut REGARD', 'France', 180, 95, 'Centre', (select id_equipe from G20_Equipe where ville = 'Lyon')),
('Ethan DUMORTIER', 'France', 192, 95, 'Ailier', (select id_equipe from G20_Equipe where ville = 'Lyon')),
('Monty IOANE', 'Australie', 180, 95, 'Ailier', (select id_equipe from G20_Equipe where ville = 'Lyon')),
('Vincent RATTEZ', 'France', 181, 89, 'Ailier', (select id_equipe from G20_Equipe where ville = 'Lyon')),
('Xavier MIGNOT', 'France', 188, 100, 'Ailier', (select id_equipe from G20_Equipe where ville = 'Lyon')),
('Alexandre TCHAPTCHET', 'France', 171, 82, 'Arrière', (select id_equipe from G20_Equipe where ville = 'Lyon')),
('Clément CASTETS', 'France', 183, 123, 'Pilier', (select id_equipe from G20_Equipe where ville = 'Paris')),
('Francisco GOMEZ KODELA', 'Argentine', 184, 122, 'Pilier', (select id_equipe from G20_Equipe where ville = 'Paris')),
('Giorgi MELIKIDZE', 'Géorgie', 179, 117, 'Pilier', (select id_equipe from G20_Equipe where ville = 'Paris')),
('Hugo DIAYE', 'France', 183, 120, 'Pilier', (select id_equipe from G20_Equipe where ville = 'Paris')),
('Moses ALO-EMILE', 'Australie', 187, 130, 'Pilier', (select id_equipe from G20_Equipe where ville = 'Paris')),
('Paul ALO-EMILE', 'Australie', 180, 132, 'Pilier', (select id_equipe from G20_Equipe where ville = 'Paris')),
('Giacomo NICOTERA', 'Italie', 183, 108, 'Talonneur', (select id_equipe from G20_Equipe where ville = 'Paris')),
('Lucas PEYRESBLANQUES', 'France', 181, 103, 'Talonneur', (select id_equipe from G20_Equipe where ville = 'Paris')),
('Luka PETRIASHVILI', 'Géorgie', 182, 108, 'Talonneur', (select id_equipe from G20_Equipe where ville = 'Paris')),
('Baptiste PESENTI', 'France', 195, 122, '2ème ligne', (select id_equipe from G20_Equipe where ville = 'Paris')),
('JJ VAN DER MESCHT', 'Afrique du sud', 200, 145, '2ème ligne', (select id_equipe from G20_Equipe where ville = 'Paris')),
('Paul GABRILLAGUES', 'France', 199, 119, '2ème ligne', (select id_equipe from G20_Equipe where ville = 'Paris')),
('Pierre-Henri AZAGOH', 'France', 198, 112, '2ème ligne', (select id_equipe from G20_Equipe where ville = 'Paris')),
('Tanginoa HALAIFONUA', 'Tonga', 196, 115, '2ème ligne', (select id_equipe from G20_Equipe where ville = 'Paris')),
('Mathieu HIRIGOYEN', 'France', 194, 103, '3ème ligne', (select id_equipe from G20_Equipe where ville = 'Paris')),
('Pierre HUGUET', 'France', 194, 111, '3ème ligne', (select id_equipe from G20_Equipe where ville = 'Paris')),
('Romain BRIATTE', 'France', 194, 107, '3ème ligne', (select id_equipe from G20_Equipe where ville = 'Paris')),
('Ryan CHAPUIS', 'France', 189, 105, '3ème ligne', (select id_equipe from G20_Equipe where ville = 'Paris')),
('Sekou MACALOU', 'France', 195, 108, '3ème ligne', (select id_equipe from G20_Equipe where ville = 'Paris')),
('Yoan TANGA', 'France', 185, 109, '3ème ligne', (select id_equipe from G20_Equipe where ville = 'Paris')),
('Brad WEBER', 'Nouvelle-Zélande', 172, 75, 'Mêlée', (select id_equipe from G20_Equipe where ville = 'Paris')),
('Jules GIMBERT', 'France', 171, 75, 'Mêlée', (select id_equipe from G20_Equipe where ville = 'Paris')),
('Louis CARBONEL', 'France', 180, 88, 'Ouverture', (select id_equipe from G20_Equipe where ville = 'Paris')),
('Louis FOURSANS-BOURDETTE', 'France', 171, 81, 'Ouverture', (select id_equipe from G20_Equipe where ville = 'Paris')),
('Zack HENRY', 'Angleterre', 182, 89, 'Ouverture', (select id_equipe from G20_Equipe where ville = 'Paris')),
('Jeremy WARD', 'Afrique du sud', 187, 92, 'Centre', (select id_equipe from G20_Equipe where ville = 'Paris')),
('Joe MARCHANT', 'Angleterre', 183, 89, 'Centre', (select id_equipe from G20_Equipe where ville = 'Paris')),
('Julien DELBOUIS', 'France', 185, 103, 'Centre', (select id_equipe from G20_Equipe where ville = 'Paris')),
('Lester ÉTIEN', 'France', 181, 102, 'Ailier', (select id_equipe from G20_Equipe where ville = 'Paris')),
('Peniasi DAKUWAQA', 'Fidji', 186, 95, 'Ailier', (select id_equipe from G20_Equipe where ville = 'Paris')),
('Pierre BOUDEHENT', 'France', 196, 107, 'Ailier', (select id_equipe from G20_Equipe where ville = 'Paris')),
('Raffaele COSTA STORTI', 'Portugal', 183, 90, 'Ailier', (select id_equipe from G20_Equipe where ville = 'Paris')),
('Samuel EZEALA', 'Espagne', 187, 99, 'Ailier', (select id_equipe from G20_Equipe where ville = 'Paris')),
('Joe JONAS', 'Afrique du sud', 180, 90, 'Arrière', (select id_equipe from G20_Equipe where ville = 'Paris')),
('Léo BARRÉ', 'France', 189, 89, 'Arrière', (select id_equipe from G20_Equipe where ville = 'Paris')),
('Cyril BAILLE', 'France', 182, 118, 'Pilier', (select id_equipe from G20_Equipe where ville = 'Toulouse')),
('David AINUU', 'Etats-Unis', 178, 125, 'Pilier', (select id_equipe from G20_Equipe where ville = 'Toulouse')),
('Dorian ALDEGHERI', 'France', 180, 119, 'Pilier', (select id_equipe from G20_Equipe where ville = 'Toulouse')),
('Hugo REILHES', 'France', 180, 108, 'Pilier', (select id_equipe from G20_Equipe where ville = 'Toulouse')),
('Nepo LAULALA', 'Samoa', 184, 133, 'Pilier', (select id_equipe from G20_Equipe where ville = 'Toulouse')),
('Rodrigue NETI', 'France', 185, 124, 'Pilier', (select id_equipe from G20_Equipe where ville = 'Toulouse')),
('Guillaume CRAMONT', 'France', 182, 107, 'Talonneur', (select id_equipe from G20_Equipe where ville = 'Toulouse')),
('Julien MARCHAND', 'France', 181, 110, 'Talonneur', (select id_equipe from G20_Equipe where ville = 'Toulouse')),
('Péato MAUVAKA', 'France', 180, 112, 'Talonneur', (select id_equipe from G20_Equipe where ville = 'Toulouse')),
('Clément VERGÉ', 'France', 200, 123, '2ème ligne', (select id_equipe from G20_Equipe where ville = 'Toulouse')),
('Emmanuel MEAFOU', 'Australie', 203, 145, '2ème ligne', (select id_equipe from G20_Equipe where ville = 'Toulouse')),
('Joshua BRENNAN', 'Irlande', 199, 118, '2ème ligne', (select id_equipe from G20_Equipe where ville = 'Toulouse')),
('Richie ARNOLD', 'Australie', 208, 127, '2ème ligne', (select id_equipe from G20_Equipe where ville = 'Toulouse')),
('Thibaud FLAMENT', 'France', 203, 116, '2ème ligne', (select id_equipe from G20_Equipe where ville = 'Toulouse')),
('Alban PLACINES', 'France', 189, 114, '3ème ligne', (select id_equipe from G20_Equipe where ville = 'Toulouse')),
('Alexandre ROUMAT', 'France', 198, 110, '3ème ligne', (select id_equipe from G20_Equipe where ville = 'Toulouse')),
('Anthony JELONCH', 'France', 195, 108, '3ème ligne', (select id_equipe from G20_Equipe where ville = 'Toulouse')),
('François CROS', 'France', 190, 111, '3ème ligne', (select id_equipe from G20_Equipe where ville = 'Toulouse')),
('Jack WILLIS', 'Angleterre', 190, 112, '3ème ligne', (select id_equipe from G20_Equipe where ville = 'Toulouse')),
('Léo BANOS', 'France', 191, 106, '3ème ligne', (select id_equipe from G20_Equipe where ville = 'Toulouse')),
('Antoine DUPONT', 'France', 174, 86, 'Mêlée', (select id_equipe from G20_Equipe where ville = 'Toulouse')),
('Naoto SAITO', 'Japon', 165, 75, 'Mêlée', (select id_equipe from G20_Equipe where ville = 'Toulouse')),
('Paul GRAOU', 'France', 177, 90, 'Mêlée', (select id_equipe from G20_Equipe where ville = 'Toulouse')),
('Romain NTAMACK', 'France', 186, 94, 'Ouverture', (select id_equipe from G20_Equipe where ville = 'Toulouse')),
('Pierre-Louis BARASSI', 'France', 188, 102, 'Centre', (select id_equipe from G20_Equipe where ville = 'Toulouse')),
('Pita AHKI', 'Nouvelle-Zélande', 189, 101, 'Centre', (select id_equipe from G20_Equipe where ville = 'Toulouse')),
('Santiago CHOCOBARES', 'Argentine', 188, 100, 'Centre', (select id_equipe from G20_Equipe where ville = 'Toulouse')),
('Dimitri DELIBES', 'France', 190, 98, 'Ailier', (select id_equipe from G20_Equipe where ville = 'Toulouse')),
('Matthis LEBEL', 'France', 185, 91, 'Ailier', (select id_equipe from G20_Equipe where ville = 'Toulouse')),
('Nelson ÉPÉE', 'France', 174, 80, 'Ailier', (select id_equipe from G20_Equipe where ville = 'Toulouse')),
('Setareki BITUNIYATA', 'Fidji', 194, 112, 'Ailier', (select id_equipe from G20_Equipe where ville = 'Toulouse')),
('Ange CAPUOZZO', 'France', 178, 82, 'Arrière', (select id_equipe from G20_Equipe where ville = 'Toulouse')),
('Blair KINGHORN', 'Ecosse', 193, 107, 'Arrière', (select id_equipe from G20_Equipe where ville = 'Toulouse')),
('Juan Cruz MALLÍA', 'Argentine', 182, 92, 'Arrière', (select id_equipe from G20_Equipe where ville = 'Toulouse')),
('Thomas RAMOS', 'France', 178, 87, 'Arrière', (select id_equipe from G20_Equipe where ville = 'Toulouse')),
('Ben TAMEIFUNA', 'Nouvelle-Zélande', 188, 151, 'Pilier', (select id_equipe from G20_Equipe where ville = 'Bordeaux')),
('Carlü SADIE', 'Afrique du sud', 182, 138, 'Pilier', (select id_equipe from G20_Equipe where ville = 'Bordeaux')),
('Jefferson POIROT', 'France', 181, 117, 'Pilier', (select id_equipe from G20_Equipe where ville = 'Bordeaux')),
('Sipili FALATEA', 'France', 183, 116, 'Pilier', (select id_equipe from G20_Equipe where ville = 'Bordeaux')),
('Toma Akino TAUFA', 'Tonga', 180, 145, 'Pilier', (select id_equipe from G20_Equipe where ville = 'Bordeaux')),
('Ugo BONIFACE', 'France', 190, 125, 'Pilier', (select id_equipe from G20_Equipe where ville = 'Bordeaux')),
('Maxime LAMOTHE', 'France', 184, 109, 'Talonneur', (select id_equipe from G20_Equipe where ville = 'Bordeaux')),
('Romain LATTERRADE', 'France', 180, 112, 'Talonneur', (select id_equipe from G20_Equipe where ville = 'Bordeaux')),
('Adam COLEMAN', 'Australie', 207, 122, '2ème ligne', (select id_equipe from G20_Equipe where ville = 'Bordeaux')),
('Alexandre RICARD', 'France', 200, 111, '2ème ligne', (select id_equipe from G20_Equipe where ville = 'Bordeaux')),
('Cyril CAZEAUX', 'France', 198, 117, '2ème ligne', (select id_equipe from G20_Equipe where ville = 'Bordeaux')),
('Guido PETTI', 'Argentine', 194, 111, '2ème ligne', (select id_equipe from G20_Equipe where ville = 'Bordeaux')),
('Jonny GRAY', 'Ecosse', 198, 122, '2ème ligne', (select id_equipe from G20_Equipe where ville = 'Bordeaux')),
('Bastien VERGNES-TAILLEFER', 'France', 194, 114, '3ème ligne', (select id_equipe from G20_Equipe where ville = 'Bordeaux')),
('Lachlan SWINTON', 'Australie', 195, 113, '3ème ligne', (select id_equipe from G20_Equipe where ville = 'Bordeaux')),
('Mahamadou DIABY', 'France', 192, 110, '3ème ligne', (select id_equipe from G20_Equipe where ville = 'Bordeaux')),
('Pete SAMU', 'Australie', 185, 102, '3ème ligne', (select id_equipe from G20_Equipe where ville = 'Bordeaux')),
('Pierre BOCHATON', 'France', 197, 103, '3ème ligne', (select id_equipe from G20_Equipe where ville = 'Bordeaux')),
('Temo MATIU', 'France', 191, 100, '3ème ligne', (select id_equipe from G20_Equipe where ville = 'Bordeaux')),
('Tevita TATAFU', 'Tonga', 184, 120, '3ème ligne', (select id_equipe from G20_Equipe where ville = 'Bordeaux')),
('Maxime LUCU', 'France', 177, 83, 'Mêlée', (select id_equipe from G20_Equipe where ville = 'Bordeaux')),
('Paul ABADIE', 'France', 176, 88, 'Mêlée', (select id_equipe from G20_Equipe where ville = 'Bordeaux')),
('Yann LESGOURGUES', 'France', 177, 82, 'Mêlée', (select id_equipe from G20_Equipe where ville = 'Bordeaux')),
('Joey CARBERY', 'Nouvelle-Zélande', 183, 86, 'Ouverture', (select id_equipe from G20_Equipe where ville = 'Bordeaux')),
('Matthieu JALIBERT', 'France', 184, 86, 'Ouverture', (select id_equipe from G20_Equipe where ville = 'Bordeaux')),
('Ben TAPUAI', 'Australie', 180, 100, 'Centre', (select id_equipe from G20_Equipe where ville = 'Bordeaux')),
('Pablo UBERTI', 'France', 185, 91, 'Centre', (select id_equipe from G20_Equipe where ville = 'Bordeaux')),
('Rohan JANSE VAN RENSBURG', 'Afrique du sud', 185, 109, 'Centre', (select id_equipe from G20_Equipe where ville = 'Bordeaux')),
('Yoram MOEFANA', 'France', 183, 95, 'Centre', (select id_equipe from G20_Equipe where ville = 'Bordeaux')),
('Arthur RETIÈRE', 'France', 173, 80, 'Ailier', (select id_equipe from G20_Equipe where ville = 'Bordeaux')),
('Damian PENAUD', 'France', 188, 97, 'Ailier', (select id_equipe from G20_Equipe where ville = 'Bordeaux')),
('Nans DUCUING', 'France', 185, 91, 'Arrière', (select id_equipe from G20_Equipe where ville = 'Bordeaux')),
('Romain BUROS', 'France', 187, 97, 'Arrière', (select id_equipe from G20_Equipe where ville = 'Bordeaux')),
('Georges-Henri COLOMBE', 'France', 193, 142, 'Pilier', (select id_equipe from G20_Equipe where ville = 'La Rochelle')),
('Joel SCLAVI', 'Argentine', 190, 139, 'Pilier', (select id_equipe from G20_Equipe where ville = 'La Rochelle')),
('Reda WARDI', 'France', 185, 111, 'Pilier', (select id_equipe from G20_Equipe where ville = 'La Rochelle')),
('Thierry PAÏVA', 'France', 184, 125, 'Pilier', (select id_equipe from G20_Equipe where ville = 'La Rochelle')),
('Uini ATONIO', 'Nouvelle-Zélande', 197, 147, 'Pilier', (select id_equipe from G20_Equipe where ville = 'La Rochelle')),
('Pierre BOURGARIT', 'France', 184, 105, 'Talonneur', (select id_equipe from G20_Equipe where ville = 'La Rochelle')),
('Quentin LESPIAUCQ', 'France', 180, 102, 'Talonneur', (select id_equipe from G20_Equipe where ville = 'La Rochelle')),
('Tolu LATU', 'Tonga', 180, 117, 'Talonneur', (select id_equipe from G20_Equipe where ville = 'La Rochelle')),
('Kane DOUGLAS', 'Australie', 202, 123, '2ème ligne', (select id_equipe from G20_Equipe where ville = 'La Rochelle')),
('Thomas LAVAULT', 'France', 199, 108, '2ème ligne', (select id_equipe from G20_Equipe where ville = 'La Rochelle')),
('Ultan DILLANE', 'Irlande', 198, 115, '2ème ligne', (select id_equipe from G20_Equipe where ville = 'La Rochelle')),
('Will SKELTON', 'Nouvelle-Zélande', 203, 145, '2ème ligne', (select id_equipe from G20_Equipe where ville = 'La Rochelle')),
('Greg ALLDRITT', 'France', 191, 114, '3ème ligne', (select id_equipe from G20_Equipe where ville = 'La Rochelle')),
('Judicaël CANCORIET', 'France', 194, 116, '3ème ligne', (select id_equipe from G20_Equipe where ville = 'La Rochelle')),
('Levani BOTIA', 'Fidji', 182, 103, '3ème ligne', (select id_equipe from G20_Equipe where ville = 'La Rochelle')),
('Matthias HADDAD', 'France', 193, 99, '3ème ligne', (select id_equipe from G20_Equipe where ville = 'La Rochelle')),
('Paul BOUDEHENT', 'France', 192, 107, '3ème ligne', (select id_equipe from G20_Equipe where ville = 'La Rochelle')),
('Tawera KERR-BARLOW', 'Nouvelle-Zélande', 187, 92, 'Mêlée', (select id_equipe from G20_Equipe where ville = 'La Rochelle')),
('Teddy IRIBAREN', 'France', 170, 70, 'Mêlée', (select id_equipe from G20_Equipe where ville = 'La Rochelle')),
('Thomas BERJON', 'France', 177, 87, 'Mêlée', (select id_equipe from G20_Equipe where ville = 'La Rochelle')),
('Antoine HASTOY', 'France', 180, 86, 'Ouverture', (select id_equipe from G20_Equipe where ville = 'La Rochelle')),
('Ihaia WEST', 'Nouvelle-Zélande', 175, 85, 'Ouverture', (select id_equipe from G20_Equipe where ville = 'La Rochelle')),
('Jonathan DANTY', 'France', 181, 110, 'Centre', (select id_equipe from G20_Equipe where ville = 'La Rochelle')),
('Jules FAVRE', 'France', 181, 93, 'Centre', (select id_equipe from G20_Equipe where ville = 'La Rochelle')),
('Ulupano SEUTENI', 'Australie', 185, 100, 'Centre', (select id_equipe from G20_Equipe where ville = 'La Rochelle')),
('Dillyn LEYDS', 'Afrique du sud', 183, 88, 'Ailier', (select id_equipe from G20_Equipe where ville = 'La Rochelle')),
('Jack NOWELL', 'Angleterre', 181, 98, 'Ailier', (select id_equipe from G20_Equipe where ville = 'La Rochelle')),
('Raymond RHULE', 'Afrique du sud', 189, 92, 'Ailier', (select id_equipe from G20_Equipe where ville = 'La Rochelle')),
('Suliasi VUNIVALU', 'Fidji', 192, 102, 'Ailier', (select id_equipe from G20_Equipe where ville = 'La Rochelle')),
('Teddy THOMAS', 'France', 185, 98, 'Ailier', (select id_equipe from G20_Equipe where ville = 'La Rochelle')),
('Brice DULIN', 'France', 176, 84, 'Arrière', (select id_equipe from G20_Equipe where ville = 'La Rochelle'))
